


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
 <link rel="icon" type="image/vnd.microsoft.icon" href="http://www.gstatic.com/codesite/ph/images/phosting.ico">
 <script type="text/javascript">
 
 
 
 var codesite_token = "eb3b4fe23ef19b1e073166e328aa0525";
 
 
 var logged_in_user_email = "obi.atueyi@gmail.com";
 
 </script>
 
 
 <title>Makefile - 
 duelreality -
 
 Project Hosting on Google Code</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
 
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/6842546122464886851/css/ph_core.css">
 
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/6842546122464886851/css/ph_detail.css" >
 
 
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/6842546122464886851/css/d_sb_20080522.css" >
 
 
 
<!--[if IE]>
 <link type="text/css" rel="stylesheet" href="http://www.gstatic.com/codesite/ph/6842546122464886851/css/d_ie.css" >
<![endif]-->
 <style type="text/css">
 .menuIcon.off { background: no-repeat url(http://www.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -42px }
 .menuIcon.on { background: no-repeat url(http://www.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 -28px }
 .menuIcon.down { background: no-repeat url(http://www.gstatic.com/codesite/ph/images/dropdown_sprite.gif) 0 0; }
 </style>
</head>
<body class="t4">
 <div id="gaia">
 
 <span>
 
 
 <b>obi.atueyi@gmail.com</b>
 
 
 
 | <a href="/u/obi.atueyi/" id="projects-dropdown" onclick="return false;"
 ><u>My favorites</u> <small>&#9660;</small></a>
 
 | <a href="/u/obi.atueyi/" onclick="_CS_click('/gb/ph/profile');" 
 title="Profile, Updates, and Settings"
 ><u>Profile</u></a>
 | <a href="https://www.google.com/accounts/Logout?continue=http%3A%2F%2Fcode.google.com%2Fp%2Fduelreality%2Fsource%2Fbrowse%2Ftrunk%2FMakefile" 
 onclick="_CS_click('/gb/ph/signout');"
 ><u>Sign out</u></a>
 
 </span>

 </div>
 <div class="gbh" style="left: 0pt;"></div>
 <div class="gbh" style="right: 0pt;"></div>
 
 
 <div style="height: 1px"></div>
<!--[if IE 6]>
<div style="text-align:center;">
Support browsers that contribute to open source, try <a href="http://www.firefox.com">Firefox</a> or <a href="http://www.google.com/chrome">Google Chrome</a>.
</div>
<![endif]-->
 <table style="padding:0px; margin: 20px 0px 0px 0px; width:100%" cellpadding="0" cellspacing="0">
 <tr style="height: 58px;">
 
 <td style="width: 55px; text-align:center;">
 <a href="/p/duelreality/">
 
 
 
 <img src="http://www.gstatic.com/codesite/ph/images/defaultlogo.png"
 alt="Project Logo">
 
 
 
 </a>
 </td>
 
 <td style="padding-left: 0.5em">
 
 <div id="pname" style="margin: 0px 0px -3px 0px">
 <a href="/p/duelreality/" style="text-decoration:none; color:#000">duelreality</a>
 
 </div>
 <div id="psum">
 <i><a id="project_summary_link" href="/p/duelreality/" style="text-decoration:none; color:#000">A 2D Tactical Combat Game</a></i>
 </div>
 
 </td>
 <td style="white-space:nowrap; text-align:right">
 
 <form action="/hosting/search">
 <input size="30" name="q" value="">
 <input type="submit" name="projectsearch" value="Search projects" >
 </form>
 
 </tr>
 </table>



 
<table id="mt" cellspacing="0" cellpadding="0" width="100%" border="0">
 <tr>
 <th onclick="if (!cancelBubble) _go('/p/duelreality/');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/duelreality/">Project&nbsp;Home</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/duelreality/downloads/list');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/duelreality/downloads/list">Downloads</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/duelreality/w/list');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/duelreality/w/list">Wiki</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/duelreality/issues/list');">
 <div class="tab inactive">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/duelreality/issues/list">Issues</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 
 
 
 <th onclick="if (!cancelBubble) _go('/p/duelreality/source/checkout');">
 <div class="tab active">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <a onclick="cancelBubble=true;" href="/p/duelreality/source/checkout">Source</a>
 </div>
 </div>
 </th><td>&nbsp;&nbsp;</td>
 
 
 <td width="100%">&nbsp;</td>
 </tr>
</table>
<table cellspacing="0" cellpadding="0" width="100%" align="center" border="0" class="st">
 <tr>
 
 
 
 
 
 
 <td>
 <div class="st2">
 <div class="isf">
 
 
 
 <span class="inst1"><a href="/p/duelreality/source/checkout">Checkout</a></span> |
 <span class="inst2"><a href="/p/duelreality/source/browse/">Browse</a></span> |
 <span class="inst3"><a href="/p/duelreality/source/list">Changes</a></span> |
 
 <form action="http://www.google.com/codesearch" method="get" style="display:inline"
 onsubmit="document.getElementById('codesearchq').value = document.getElementById('origq').value + ' package:http://duelreality\\.googlecode\\.com'">
 <input type="hidden" name="q" id="codesearchq" value="">
 <input maxlength="2048" size="35" id="origq" name="origq" value="" title="Google Code Search" style="font-size:92%">&nbsp;<input type="submit" value="Search Trunk" name="btnG" style="font-size:92%">
 
 
 
 </form>
 </div>
</div>

 </td>
 
 
 
 
 
 <td height="4" align="right" valign="top" class="bevel-right">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 </td>
 </tr>
</table>
<script type="text/javascript">
 var cancelBubble = false;
 function _go(url) { document.location = url; }
</script>


<div id="maincol"
 
>

 
<!-- IE -->



<div class="expand">


<style type="text/css">
 #file_flipper { display: inline; float: right; white-space: nowrap; }
 #file_flipper.hidden { display: none; }
 #file_flipper .pagelink { color: #0000CC; text-decoration: underline; }
 #file_flipper #visiblefiles { padding-left: 0.5em; padding-right: 0.5em; }
</style>
<div id="nav_and_rev" class="heading">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner" id="bub">
 <div class="bub-top">
 <div class="pagination" style="margin-left: 2em">
 <table cellpadding="0" cellspacing="0" class="flipper">
 <tbody>
 <tr>
 
 <td><b>r17</b></td>
 
 </tr>
 </tbody>
 </table>
 </div>
 
 <div class="" style="vertical-align: top">
 <div class="src_crumbs src_nav">
 <strong class="src_nav">Source path:&nbsp;</strong>
 <span id="crumb_root">
 
 <a href="/p/duelreality/source/browse/">svn</a>/&nbsp;</span>
 <span id="crumb_links" class="ifClosed"><a href="/p/duelreality/source/browse/trunk/">trunk</a><span class="sp">/&nbsp;</span>Makefile</span>
 
 
 </div>
 
 </div>
 <div style="clear:both"></div>
 </div>
 </div>
</div>

<style type="text/css">
 
  tr.inline_comment {
 background: #fff;
 vertical-align: top;
 }
 div.draft, div.published {
 padding: .3em;
 border: 1px solid #999; 
 margin-bottom: .1em;
 font-family: arial, sans-serif;
 max-width: 60em;
 }
 div.draft {
 background: #ffa;
 } 
 div.published {
 background: #e5ecf9;
 }
 div.published .body, div.draft .body {
 padding: .5em .1em .1em .1em;
 max-width: 60em;
 white-space: pre-wrap;
 white-space: -moz-pre-wrap;
 white-space: -pre-wrap;
 white-space: -o-pre-wrap;
 word-wrap: break-word;
 }
 div.draft .actions {
 margin-left: 1em;
 font-size: 90%;
 }
 div.draft form {
 padding: .5em .5em .5em 0;
 }
 div.draft textarea, div.published textarea {
 width: 95%;
 height: 10em;
 font-family: arial, sans-serif;
 margin-bottom: .5em;
 }


 
 .nocursor, .nocursor td, .cursor_hidden, .cursor_hidden td {
 background-color: white;
 height: 2px;
 }
 .cursor, .cursor td {
 background-color: darkblue;
 height: 2px;
 display: '';
 }

</style>
<div class="fc">
 


<table class="opened" id="review_comment_area"><tr>
<td id="nums">
<pre><table width="100%"><tr class="nocursor"><td></td></tr></table></pre>

<pre><table width="100%"><tr id="gr_svn12_1"><td id="1"><a href="#1">1</a></td></tr
><tr id="gr_svn12_2"><td id="2"><a href="#2">2</a></td></tr
><tr id="gr_svn12_3"><td id="3"><a href="#3">3</a></td></tr
><tr id="gr_svn12_4"><td id="4"><a href="#4">4</a></td></tr
><tr id="gr_svn12_5"><td id="5"><a href="#5">5</a></td></tr
><tr id="gr_svn12_6"><td id="6"><a href="#6">6</a></td></tr
><tr id="gr_svn12_7"><td id="7"><a href="#7">7</a></td></tr
><tr id="gr_svn12_8"><td id="8"><a href="#8">8</a></td></tr
><tr id="gr_svn12_9"><td id="9"><a href="#9">9</a></td></tr
><tr id="gr_svn12_10"><td id="10"><a href="#10">10</a></td></tr
><tr id="gr_svn12_11"><td id="11"><a href="#11">11</a></td></tr
><tr id="gr_svn12_12"><td id="12"><a href="#12">12</a></td></tr
><tr id="gr_svn12_13"><td id="13"><a href="#13">13</a></td></tr
><tr id="gr_svn12_14"><td id="14"><a href="#14">14</a></td></tr
><tr id="gr_svn12_15"><td id="15"><a href="#15">15</a></td></tr
><tr id="gr_svn12_16"><td id="16"><a href="#16">16</a></td></tr
><tr id="gr_svn12_17"><td id="17"><a href="#17">17</a></td></tr
><tr id="gr_svn12_18"><td id="18"><a href="#18">18</a></td></tr
><tr id="gr_svn12_19"><td id="19"><a href="#19">19</a></td></tr
><tr id="gr_svn12_20"><td id="20"><a href="#20">20</a></td></tr
><tr id="gr_svn12_21"><td id="21"><a href="#21">21</a></td></tr
><tr id="gr_svn12_22"><td id="22"><a href="#22">22</a></td></tr
><tr id="gr_svn12_23"><td id="23"><a href="#23">23</a></td></tr
><tr id="gr_svn12_24"><td id="24"><a href="#24">24</a></td></tr
><tr id="gr_svn12_25"><td id="25"><a href="#25">25</a></td></tr
><tr id="gr_svn12_26"><td id="26"><a href="#26">26</a></td></tr
><tr id="gr_svn12_27"><td id="27"><a href="#27">27</a></td></tr
><tr id="gr_svn12_28"><td id="28"><a href="#28">28</a></td></tr
><tr id="gr_svn12_29"><td id="29"><a href="#29">29</a></td></tr
><tr id="gr_svn12_30"><td id="30"><a href="#30">30</a></td></tr
><tr id="gr_svn12_31"><td id="31"><a href="#31">31</a></td></tr
><tr id="gr_svn12_32"><td id="32"><a href="#32">32</a></td></tr
><tr id="gr_svn12_33"><td id="33"><a href="#33">33</a></td></tr
><tr id="gr_svn12_34"><td id="34"><a href="#34">34</a></td></tr
><tr id="gr_svn12_35"><td id="35"><a href="#35">35</a></td></tr
><tr id="gr_svn12_36"><td id="36"><a href="#36">36</a></td></tr
><tr id="gr_svn12_37"><td id="37"><a href="#37">37</a></td></tr
><tr id="gr_svn12_38"><td id="38"><a href="#38">38</a></td></tr
><tr id="gr_svn12_39"><td id="39"><a href="#39">39</a></td></tr
><tr id="gr_svn12_40"><td id="40"><a href="#40">40</a></td></tr
><tr id="gr_svn12_41"><td id="41"><a href="#41">41</a></td></tr
><tr id="gr_svn12_42"><td id="42"><a href="#42">42</a></td></tr
><tr id="gr_svn12_43"><td id="43"><a href="#43">43</a></td></tr
><tr id="gr_svn12_44"><td id="44"><a href="#44">44</a></td></tr
><tr id="gr_svn12_45"><td id="45"><a href="#45">45</a></td></tr
><tr id="gr_svn12_46"><td id="46"><a href="#46">46</a></td></tr
><tr id="gr_svn12_47"><td id="47"><a href="#47">47</a></td></tr
><tr id="gr_svn12_48"><td id="48"><a href="#48">48</a></td></tr
><tr id="gr_svn12_49"><td id="49"><a href="#49">49</a></td></tr
><tr id="gr_svn12_50"><td id="50"><a href="#50">50</a></td></tr
><tr id="gr_svn12_51"><td id="51"><a href="#51">51</a></td></tr
><tr id="gr_svn12_52"><td id="52"><a href="#52">52</a></td></tr
><tr id="gr_svn12_53"><td id="53"><a href="#53">53</a></td></tr
><tr id="gr_svn12_54"><td id="54"><a href="#54">54</a></td></tr
><tr id="gr_svn12_55"><td id="55"><a href="#55">55</a></td></tr
><tr id="gr_svn12_56"><td id="56"><a href="#56">56</a></td></tr
><tr id="gr_svn12_57"><td id="57"><a href="#57">57</a></td></tr
><tr id="gr_svn12_58"><td id="58"><a href="#58">58</a></td></tr
><tr id="gr_svn12_59"><td id="59"><a href="#59">59</a></td></tr
><tr id="gr_svn12_60"><td id="60"><a href="#60">60</a></td></tr
><tr id="gr_svn12_61"><td id="61"><a href="#61">61</a></td></tr
><tr id="gr_svn12_62"><td id="62"><a href="#62">62</a></td></tr
><tr id="gr_svn12_63"><td id="63"><a href="#63">63</a></td></tr
><tr id="gr_svn12_64"><td id="64"><a href="#64">64</a></td></tr
><tr id="gr_svn12_65"><td id="65"><a href="#65">65</a></td></tr
><tr id="gr_svn12_66"><td id="66"><a href="#66">66</a></td></tr
><tr id="gr_svn12_67"><td id="67"><a href="#67">67</a></td></tr
><tr id="gr_svn12_68"><td id="68"><a href="#68">68</a></td></tr
><tr id="gr_svn12_69"><td id="69"><a href="#69">69</a></td></tr
><tr id="gr_svn12_70"><td id="70"><a href="#70">70</a></td></tr
><tr id="gr_svn12_71"><td id="71"><a href="#71">71</a></td></tr
><tr id="gr_svn12_72"><td id="72"><a href="#72">72</a></td></tr
><tr id="gr_svn12_73"><td id="73"><a href="#73">73</a></td></tr
><tr id="gr_svn12_74"><td id="74"><a href="#74">74</a></td></tr
><tr id="gr_svn12_75"><td id="75"><a href="#75">75</a></td></tr
><tr id="gr_svn12_76"><td id="76"><a href="#76">76</a></td></tr
><tr id="gr_svn12_77"><td id="77"><a href="#77">77</a></td></tr
><tr id="gr_svn12_78"><td id="78"><a href="#78">78</a></td></tr
><tr id="gr_svn12_79"><td id="79"><a href="#79">79</a></td></tr
><tr id="gr_svn12_80"><td id="80"><a href="#80">80</a></td></tr
><tr id="gr_svn12_81"><td id="81"><a href="#81">81</a></td></tr
><tr id="gr_svn12_82"><td id="82"><a href="#82">82</a></td></tr
><tr id="gr_svn12_83"><td id="83"><a href="#83">83</a></td></tr
><tr id="gr_svn12_84"><td id="84"><a href="#84">84</a></td></tr
><tr id="gr_svn12_85"><td id="85"><a href="#85">85</a></td></tr
><tr id="gr_svn12_86"><td id="86"><a href="#86">86</a></td></tr
><tr id="gr_svn12_87"><td id="87"><a href="#87">87</a></td></tr
><tr id="gr_svn12_88"><td id="88"><a href="#88">88</a></td></tr
><tr id="gr_svn12_89"><td id="89"><a href="#89">89</a></td></tr
><tr id="gr_svn12_90"><td id="90"><a href="#90">90</a></td></tr
><tr id="gr_svn12_91"><td id="91"><a href="#91">91</a></td></tr
><tr id="gr_svn12_92"><td id="92"><a href="#92">92</a></td></tr
><tr id="gr_svn12_93"><td id="93"><a href="#93">93</a></td></tr
><tr id="gr_svn12_94"><td id="94"><a href="#94">94</a></td></tr
><tr id="gr_svn12_95"><td id="95"><a href="#95">95</a></td></tr
><tr id="gr_svn12_96"><td id="96"><a href="#96">96</a></td></tr
><tr id="gr_svn12_97"><td id="97"><a href="#97">97</a></td></tr
><tr id="gr_svn12_98"><td id="98"><a href="#98">98</a></td></tr
><tr id="gr_svn12_99"><td id="99"><a href="#99">99</a></td></tr
><tr id="gr_svn12_100"><td id="100"><a href="#100">100</a></td></tr
><tr id="gr_svn12_101"><td id="101"><a href="#101">101</a></td></tr
><tr id="gr_svn12_102"><td id="102"><a href="#102">102</a></td></tr
><tr id="gr_svn12_103"><td id="103"><a href="#103">103</a></td></tr
><tr id="gr_svn12_104"><td id="104"><a href="#104">104</a></td></tr
><tr id="gr_svn12_105"><td id="105"><a href="#105">105</a></td></tr
><tr id="gr_svn12_106"><td id="106"><a href="#106">106</a></td></tr
><tr id="gr_svn12_107"><td id="107"><a href="#107">107</a></td></tr
><tr id="gr_svn12_108"><td id="108"><a href="#108">108</a></td></tr
><tr id="gr_svn12_109"><td id="109"><a href="#109">109</a></td></tr
><tr id="gr_svn12_110"><td id="110"><a href="#110">110</a></td></tr
><tr id="gr_svn12_111"><td id="111"><a href="#111">111</a></td></tr
><tr id="gr_svn12_112"><td id="112"><a href="#112">112</a></td></tr
><tr id="gr_svn12_113"><td id="113"><a href="#113">113</a></td></tr
><tr id="gr_svn12_114"><td id="114"><a href="#114">114</a></td></tr
><tr id="gr_svn12_115"><td id="115"><a href="#115">115</a></td></tr
><tr id="gr_svn12_116"><td id="116"><a href="#116">116</a></td></tr
><tr id="gr_svn12_117"><td id="117"><a href="#117">117</a></td></tr
><tr id="gr_svn12_118"><td id="118"><a href="#118">118</a></td></tr
><tr id="gr_svn12_119"><td id="119"><a href="#119">119</a></td></tr
><tr id="gr_svn12_120"><td id="120"><a href="#120">120</a></td></tr
><tr id="gr_svn12_121"><td id="121"><a href="#121">121</a></td></tr
><tr id="gr_svn12_122"><td id="122"><a href="#122">122</a></td></tr
><tr id="gr_svn12_123"><td id="123"><a href="#123">123</a></td></tr
><tr id="gr_svn12_124"><td id="124"><a href="#124">124</a></td></tr
><tr id="gr_svn12_125"><td id="125"><a href="#125">125</a></td></tr
><tr id="gr_svn12_126"><td id="126"><a href="#126">126</a></td></tr
><tr id="gr_svn12_127"><td id="127"><a href="#127">127</a></td></tr
><tr id="gr_svn12_128"><td id="128"><a href="#128">128</a></td></tr
><tr id="gr_svn12_129"><td id="129"><a href="#129">129</a></td></tr
><tr id="gr_svn12_130"><td id="130"><a href="#130">130</a></td></tr
><tr id="gr_svn12_131"><td id="131"><a href="#131">131</a></td></tr
><tr id="gr_svn12_132"><td id="132"><a href="#132">132</a></td></tr
><tr id="gr_svn12_133"><td id="133"><a href="#133">133</a></td></tr
><tr id="gr_svn12_134"><td id="134"><a href="#134">134</a></td></tr
><tr id="gr_svn12_135"><td id="135"><a href="#135">135</a></td></tr
><tr id="gr_svn12_136"><td id="136"><a href="#136">136</a></td></tr
><tr id="gr_svn12_137"><td id="137"><a href="#137">137</a></td></tr
><tr id="gr_svn12_138"><td id="138"><a href="#138">138</a></td></tr
><tr id="gr_svn12_139"><td id="139"><a href="#139">139</a></td></tr
><tr id="gr_svn12_140"><td id="140"><a href="#140">140</a></td></tr
><tr id="gr_svn12_141"><td id="141"><a href="#141">141</a></td></tr
><tr id="gr_svn12_142"><td id="142"><a href="#142">142</a></td></tr
><tr id="gr_svn12_143"><td id="143"><a href="#143">143</a></td></tr
><tr id="gr_svn12_144"><td id="144"><a href="#144">144</a></td></tr
><tr id="gr_svn12_145"><td id="145"><a href="#145">145</a></td></tr
></table></pre>

<pre><table width="100%"><tr class="nocursor"><td></td></tr></table></pre>
</td>
<td id="lines">
<pre class="prettyprint"><table width="100%"><tr class="cursor_stop cursor_hidden"><td></td></tr></table></pre>

<pre class="prettyprint "><table><tr
id=sl_svn12_1><td class="source">#############################################################################<br></td></tr
><tr
id=sl_svn12_2><td class="source"># Makefile for building: DuelReality<br></td></tr
><tr
id=sl_svn12_3><td class="source"># Generated by qmake (2.01a) (Qt 4.6.1) on: Fri Feb 19 17:36:10 2010<br></td></tr
><tr
id=sl_svn12_4><td class="source"># Project:  DuelReality.pro<br></td></tr
><tr
id=sl_svn12_5><td class="source"># Template: app<br></td></tr
><tr
id=sl_svn12_6><td class="source"># Command: c:\qt\2010.01\qt\bin\qmake.exe -spec c:\Qt\2010.01\qt\mkspecs\win32-g++ -win32 -o Makefile DuelReality.pro<br></td></tr
><tr
id=sl_svn12_7><td class="source">#############################################################################<br></td></tr
><tr
id=sl_svn12_8><td class="source"><br></td></tr
><tr
id=sl_svn12_9><td class="source">first: debug<br></td></tr
><tr
id=sl_svn12_10><td class="source">install: debug-install<br></td></tr
><tr
id=sl_svn12_11><td class="source">uninstall: debug-uninstall<br></td></tr
><tr
id=sl_svn12_12><td class="source">MAKEFILE      = Makefile<br></td></tr
><tr
id=sl_svn12_13><td class="source">QMAKE         = c:\qt\2010.01\qt\bin\qmake.exe<br></td></tr
><tr
id=sl_svn12_14><td class="source">DEL_FILE      = del<br></td></tr
><tr
id=sl_svn12_15><td class="source">CHK_DIR_EXISTS= if not exist<br></td></tr
><tr
id=sl_svn12_16><td class="source">MKDIR         = mkdir<br></td></tr
><tr
id=sl_svn12_17><td class="source">COPY          = copy /y<br></td></tr
><tr
id=sl_svn12_18><td class="source">COPY_FILE     = $(COPY)<br></td></tr
><tr
id=sl_svn12_19><td class="source">COPY_DIR      = xcopy /s /q /y /i<br></td></tr
><tr
id=sl_svn12_20><td class="source">INSTALL_FILE  = $(COPY_FILE)<br></td></tr
><tr
id=sl_svn12_21><td class="source">INSTALL_PROGRAM = $(COPY_FILE)<br></td></tr
><tr
id=sl_svn12_22><td class="source">INSTALL_DIR   = $(COPY_DIR)<br></td></tr
><tr
id=sl_svn12_23><td class="source">DEL_FILE      = del<br></td></tr
><tr
id=sl_svn12_24><td class="source">SYMLINK       = <br></td></tr
><tr
id=sl_svn12_25><td class="source">DEL_DIR       = rmdir<br></td></tr
><tr
id=sl_svn12_26><td class="source">MOVE          = move<br></td></tr
><tr
id=sl_svn12_27><td class="source">CHK_DIR_EXISTS= if not exist<br></td></tr
><tr
id=sl_svn12_28><td class="source">MKDIR         = mkdir<br></td></tr
><tr
id=sl_svn12_29><td class="source">SUBTARGETS    =  \<br></td></tr
><tr
id=sl_svn12_30><td class="source">		debug \<br></td></tr
><tr
id=sl_svn12_31><td class="source">		release<br></td></tr
><tr
id=sl_svn12_32><td class="source"><br></td></tr
><tr
id=sl_svn12_33><td class="source">debug: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_34><td class="source">	$(MAKE) -f $(MAKEFILE).Debug<br></td></tr
><tr
id=sl_svn12_35><td class="source">debug-make_default: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_36><td class="source">	$(MAKE) -f $(MAKEFILE).Debug <br></td></tr
><tr
id=sl_svn12_37><td class="source">debug-make_first: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_38><td class="source">	$(MAKE) -f $(MAKEFILE).Debug first<br></td></tr
><tr
id=sl_svn12_39><td class="source">debug-all: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_40><td class="source">	$(MAKE) -f $(MAKEFILE).Debug all<br></td></tr
><tr
id=sl_svn12_41><td class="source">debug-clean: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_42><td class="source">	$(MAKE) -f $(MAKEFILE).Debug clean<br></td></tr
><tr
id=sl_svn12_43><td class="source">debug-distclean: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_44><td class="source">	$(MAKE) -f $(MAKEFILE).Debug distclean<br></td></tr
><tr
id=sl_svn12_45><td class="source">debug-install: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_46><td class="source">	$(MAKE) -f $(MAKEFILE).Debug install<br></td></tr
><tr
id=sl_svn12_47><td class="source">debug-uninstall: $(MAKEFILE).Debug FORCE<br></td></tr
><tr
id=sl_svn12_48><td class="source">	$(MAKE) -f $(MAKEFILE).Debug uninstall<br></td></tr
><tr
id=sl_svn12_49><td class="source">release: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_50><td class="source">	$(MAKE) -f $(MAKEFILE).Release<br></td></tr
><tr
id=sl_svn12_51><td class="source">release-make_default: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_52><td class="source">	$(MAKE) -f $(MAKEFILE).Release <br></td></tr
><tr
id=sl_svn12_53><td class="source">release-make_first: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_54><td class="source">	$(MAKE) -f $(MAKEFILE).Release first<br></td></tr
><tr
id=sl_svn12_55><td class="source">release-all: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_56><td class="source">	$(MAKE) -f $(MAKEFILE).Release all<br></td></tr
><tr
id=sl_svn12_57><td class="source">release-clean: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_58><td class="source">	$(MAKE) -f $(MAKEFILE).Release clean<br></td></tr
><tr
id=sl_svn12_59><td class="source">release-distclean: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_60><td class="source">	$(MAKE) -f $(MAKEFILE).Release distclean<br></td></tr
><tr
id=sl_svn12_61><td class="source">release-install: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_62><td class="source">	$(MAKE) -f $(MAKEFILE).Release install<br></td></tr
><tr
id=sl_svn12_63><td class="source">release-uninstall: $(MAKEFILE).Release FORCE<br></td></tr
><tr
id=sl_svn12_64><td class="source">	$(MAKE) -f $(MAKEFILE).Release uninstall<br></td></tr
><tr
id=sl_svn12_65><td class="source"><br></td></tr
><tr
id=sl_svn12_66><td class="source">Makefile: DuelReality.pro  c:/Qt/2010.01/qt/mkspecs/win32-g++/qmake.conf c:/Qt/2010.01/qt/mkspecs/qconfig.pri \<br></td></tr
><tr
id=sl_svn12_67><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/qt_functions.prf \<br></td></tr
><tr
id=sl_svn12_68><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/qt_config.prf \<br></td></tr
><tr
id=sl_svn12_69><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/exclusive_builds.prf \<br></td></tr
><tr
id=sl_svn12_70><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/default_pre.prf \<br></td></tr
><tr
id=sl_svn12_71><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/default_pre.prf \<br></td></tr
><tr
id=sl_svn12_72><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/debug.prf \<br></td></tr
><tr
id=sl_svn12_73><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/debug_and_release.prf \<br></td></tr
><tr
id=sl_svn12_74><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/default_post.prf \<br></td></tr
><tr
id=sl_svn12_75><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/default_post.prf \<br></td></tr
><tr
id=sl_svn12_76><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/rtti.prf \<br></td></tr
><tr
id=sl_svn12_77><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/exceptions.prf \<br></td></tr
><tr
id=sl_svn12_78><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/stl.prf \<br></td></tr
><tr
id=sl_svn12_79><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/shared.prf \<br></td></tr
><tr
id=sl_svn12_80><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/warn_on.prf \<br></td></tr
><tr
id=sl_svn12_81><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/qt.prf \<br></td></tr
><tr
id=sl_svn12_82><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/opengl.prf \<br></td></tr
><tr
id=sl_svn12_83><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/thread.prf \<br></td></tr
><tr
id=sl_svn12_84><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/moc.prf \<br></td></tr
><tr
id=sl_svn12_85><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/win32/windows.prf \<br></td></tr
><tr
id=sl_svn12_86><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/resources.prf \<br></td></tr
><tr
id=sl_svn12_87><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/uic.prf \<br></td></tr
><tr
id=sl_svn12_88><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/yacc.prf \<br></td></tr
><tr
id=sl_svn12_89><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/lex.prf \<br></td></tr
><tr
id=sl_svn12_90><td class="source">		c:/Qt/2010.01/qt/mkspecs/features/include_source_dir.prf \<br></td></tr
><tr
id=sl_svn12_91><td class="source">		c:/Qt/2010.01/qt/lib/qtmaind.prl<br></td></tr
><tr
id=sl_svn12_92><td class="source">	$(QMAKE) -spec c:\Qt\2010.01\qt\mkspecs\win32-g++ -win32 -o Makefile DuelReality.pro<br></td></tr
><tr
id=sl_svn12_93><td class="source">c:\Qt\2010.01\qt\mkspecs\qconfig.pri:<br></td></tr
><tr
id=sl_svn12_94><td class="source">c:\Qt\2010.01\qt\mkspecs\features\qt_functions.prf:<br></td></tr
><tr
id=sl_svn12_95><td class="source">c:\Qt\2010.01\qt\mkspecs\features\qt_config.prf:<br></td></tr
><tr
id=sl_svn12_96><td class="source">c:\Qt\2010.01\qt\mkspecs\features\exclusive_builds.prf:<br></td></tr
><tr
id=sl_svn12_97><td class="source">c:\Qt\2010.01\qt\mkspecs\features\default_pre.prf:<br></td></tr
><tr
id=sl_svn12_98><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\default_pre.prf:<br></td></tr
><tr
id=sl_svn12_99><td class="source">c:\Qt\2010.01\qt\mkspecs\features\debug.prf:<br></td></tr
><tr
id=sl_svn12_100><td class="source">c:\Qt\2010.01\qt\mkspecs\features\debug_and_release.prf:<br></td></tr
><tr
id=sl_svn12_101><td class="source">c:\Qt\2010.01\qt\mkspecs\features\default_post.prf:<br></td></tr
><tr
id=sl_svn12_102><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\default_post.prf:<br></td></tr
><tr
id=sl_svn12_103><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\rtti.prf:<br></td></tr
><tr
id=sl_svn12_104><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\exceptions.prf:<br></td></tr
><tr
id=sl_svn12_105><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\stl.prf:<br></td></tr
><tr
id=sl_svn12_106><td class="source">c:\Qt\2010.01\qt\mkspecs\features\shared.prf:<br></td></tr
><tr
id=sl_svn12_107><td class="source">c:\Qt\2010.01\qt\mkspecs\features\warn_on.prf:<br></td></tr
><tr
id=sl_svn12_108><td class="source">c:\Qt\2010.01\qt\mkspecs\features\qt.prf:<br></td></tr
><tr
id=sl_svn12_109><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\opengl.prf:<br></td></tr
><tr
id=sl_svn12_110><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\thread.prf:<br></td></tr
><tr
id=sl_svn12_111><td class="source">c:\Qt\2010.01\qt\mkspecs\features\moc.prf:<br></td></tr
><tr
id=sl_svn12_112><td class="source">c:\Qt\2010.01\qt\mkspecs\features\win32\windows.prf:<br></td></tr
><tr
id=sl_svn12_113><td class="source">c:\Qt\2010.01\qt\mkspecs\features\resources.prf:<br></td></tr
><tr
id=sl_svn12_114><td class="source">c:\Qt\2010.01\qt\mkspecs\features\uic.prf:<br></td></tr
><tr
id=sl_svn12_115><td class="source">c:\Qt\2010.01\qt\mkspecs\features\yacc.prf:<br></td></tr
><tr
id=sl_svn12_116><td class="source">c:\Qt\2010.01\qt\mkspecs\features\lex.prf:<br></td></tr
><tr
id=sl_svn12_117><td class="source">c:\Qt\2010.01\qt\mkspecs\features\include_source_dir.prf:<br></td></tr
><tr
id=sl_svn12_118><td class="source">c:\Qt\2010.01\qt\lib\qtmaind.prl:<br></td></tr
><tr
id=sl_svn12_119><td class="source">qmake: qmake_all FORCE<br></td></tr
><tr
id=sl_svn12_120><td class="source">	@$(QMAKE) -spec c:\Qt\2010.01\qt\mkspecs\win32-g++ -win32 -o Makefile DuelReality.pro<br></td></tr
><tr
id=sl_svn12_121><td class="source"><br></td></tr
><tr
id=sl_svn12_122><td class="source">qmake_all: FORCE<br></td></tr
><tr
id=sl_svn12_123><td class="source"><br></td></tr
><tr
id=sl_svn12_124><td class="source">make_default: debug-make_default release-make_default FORCE<br></td></tr
><tr
id=sl_svn12_125><td class="source">make_first: debug-make_first release-make_first FORCE<br></td></tr
><tr
id=sl_svn12_126><td class="source">all: debug-all release-all FORCE<br></td></tr
><tr
id=sl_svn12_127><td class="source">clean: debug-clean release-clean FORCE<br></td></tr
><tr
id=sl_svn12_128><td class="source">distclean: debug-distclean release-distclean FORCE<br></td></tr
><tr
id=sl_svn12_129><td class="source">	-$(DEL_FILE) Makefile<br></td></tr
><tr
id=sl_svn12_130><td class="source"><br></td></tr
><tr
id=sl_svn12_131><td class="source">debug-mocclean: $(MAKEFILE).Debug<br></td></tr
><tr
id=sl_svn12_132><td class="source">	$(MAKE) -f $(MAKEFILE).Debug mocclean<br></td></tr
><tr
id=sl_svn12_133><td class="source">release-mocclean: $(MAKEFILE).Release<br></td></tr
><tr
id=sl_svn12_134><td class="source">	$(MAKE) -f $(MAKEFILE).Release mocclean<br></td></tr
><tr
id=sl_svn12_135><td class="source">mocclean: debug-mocclean release-mocclean<br></td></tr
><tr
id=sl_svn12_136><td class="source"><br></td></tr
><tr
id=sl_svn12_137><td class="source">debug-mocables: $(MAKEFILE).Debug<br></td></tr
><tr
id=sl_svn12_138><td class="source">	$(MAKE) -f $(MAKEFILE).Debug mocables<br></td></tr
><tr
id=sl_svn12_139><td class="source">release-mocables: $(MAKEFILE).Release<br></td></tr
><tr
id=sl_svn12_140><td class="source">	$(MAKE) -f $(MAKEFILE).Release mocables<br></td></tr
><tr
id=sl_svn12_141><td class="source">mocables: debug-mocables release-mocables<br></td></tr
><tr
id=sl_svn12_142><td class="source">FORCE:<br></td></tr
><tr
id=sl_svn12_143><td class="source"><br></td></tr
><tr
id=sl_svn12_144><td class="source">$(MAKEFILE).Debug: Makefile<br></td></tr
><tr
id=sl_svn12_145><td class="source">$(MAKEFILE).Release: Makefile<br></td></tr
></table></pre>

<pre class="prettyprint"><table width="100%"><tr class="cursor_stop cursor_hidden"><td></td></tr></table></pre>
</td>
</tr></table>



 <div id="log">
 <div style="text-align:right">
 <a class="ifCollapse" href="#" onclick="_toggleMeta('', 'p', 'duelreality', this)">Show details</a>
 <a class="ifExpand" href="#" onclick="_toggleMeta('', 'p', 'duelreality', this)">Hide details</a>
 </div>
 <div class="ifExpand">
 
 <div class="pmeta_bubble_bg" style="border:1px solid white">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <div id="changelog">
 <p>Change log</p>
 <div>
 <a href="/p/duelreality/source/detail?spec=svn17&r=12">r12</a>
 by tomasu
 on Today (84 minutes ago)
 &nbsp; <a href="/p/duelreality/source/diff?spec=svn17&r=12&amp;format=side&amp;path=/trunk/Makefile&amp;old_path=/trunk/Makefile&amp;old=">Diff</a>
 </div>
 <pre>Added makefiles for simplicity.  - Tom
Calloway</pre>
 </div>
 
 
 
 
 
 
 <script type="text/javascript">
 var detail_url = '/p/duelreality/source/detail?r=12&spec=svn17';
 var publish_url = '/p/duelreality/source/detail?r=12&spec=svn17#publish';
 // describe the paths of this revision in javascript.
 var changed_paths = [];
 var changed_urls = [];
 
 changed_paths.push('/trunk/Makefile');
 changed_urls.push('/p/duelreality/source/browse/trunk/Makefile?r=12&spec=svn17');
 
 var selected_path = '/trunk/Makefile';
 
 
 function getCurrentPageIndex() {
 for (var i = 0; i < changed_paths.length; i++) {
 if (selected_path == changed_paths[i]) {
 return i;
 }
 }
 }
 function getNextPage() {
 var i = getCurrentPageIndex();
 if (i < changed_paths.length - 1) {
 return changed_urls[i + 1];
 }
 return null;
 }
 function getPreviousPage() {
 var i = getCurrentPageIndex();
 if (i > 0) {
 return changed_urls[i - 1];
 }
 return null;
 }
 function gotoNextPage() {
 var page = getNextPage();
 if (!page) {
 page = detail_url;
 }
 window.location = page;
 }
 function gotoPreviousPage() {
 var page = getPreviousPage();
 if (!page) {
 page = detail_url;
 }
 window.location = page;
 }
 function gotoDetailPage() {
 window.location = detail_url;
 }
 function gotoPublishPage() {
 window.location = publish_url;
 }
</script>
 
 <style type="text/css">
 #review_nav {
 border-top: 3px solid white;
 padding-top: 6px;
 margin-top: 1em;
 }
 #review_nav td {
 vertical-align: middle;
 }
 #review_nav select {
 margin: .5em 0;
 }
 </style>
 <div id="review_nav">
 <table><tr><td>Go to:&nbsp;</td><td>
 <select name="files_in_rev" onchange="window.location=this.value">
 
 <option value="/p/duelreality/source/browse/trunk/Makefile?r=12&amp;spec=svn17"
 selected="selected"
 >/trunk/Makefile</option>
 
 </select>
 </td></tr></table>
 
 
 




 
 </div>
 
 
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 <div class="pmeta_bubble_bg" style="border:1px solid white">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <div id="older_bubble">
 <p>Older revisions</p>
 
 <a href="/p/duelreality/source/list?path=/trunk/Makefile&start=12">All revisions of this file</a>
 </div>
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 <div class="pmeta_bubble_bg" style="border:1px solid white">
 <div class="round4"></div>
 <div class="round2"></div>
 <div class="round1"></div>
 <div class="box-inner">
 <div id="fileinfo_bubble">
 <p>File info</p>
 
 <div>Size: 5986 bytes,
 145 lines</div>
 
 <div><a href="http://duelreality.googlecode.com/svn/trunk/Makefile">View raw file</a></div>
 </div>
 
 </div>
 <div class="round1"></div>
 <div class="round2"></div>
 <div class="round4"></div>
 </div>
 </div>
 </div>


</div>
</div>

 <script src="http://www.gstatic.com/codesite/ph/6842546122464886851/js/prettify/prettify.js"></script>

<script type="text/javascript">prettyPrint();</script>

<script src="http://www.gstatic.com/codesite/ph/6842546122464886851/js/source_file_scripts.js"></script>

 <script type="text/javascript" src="http://kibbles.googlecode.com/files/kibbles-1.3.1.comp.js"></script>
 <script type="text/javascript">
 var lastStop = null;
 var initilized = false;
 
 function updateCursor(next, prev) {
 if (prev && prev.element) {
 prev.element.className = 'cursor_stop cursor_hidden';
 }
 if (next && next.element) {
 next.element.className = 'cursor_stop cursor';
 lastStop = next.index;
 }
 }
 
 function pubRevealed(data) {
 updateCursorForCell(data.cellId, 'cursor_stop cursor_hidden');
 if (initilized) {
 reloadCursors();
 }
 }
 
 function draftRevealed(data) {
 updateCursorForCell(data.cellId, 'cursor_stop cursor_hidden');
 if (initilized) {
 reloadCursors();
 }
 }
 
 function draftDestroyed(data) {
 updateCursorForCell(data.cellId, 'nocursor');
 if (initilized) {
 reloadCursors();
 }
 }
 function reloadCursors() {
 kibbles.skipper.reset();
 loadCursors();
 if (lastStop != null) {
 kibbles.skipper.setCurrentStop(lastStop);
 }
 }
 // possibly the simplest way to insert any newly added comments
 // is to update the class of the corresponding cursor row,
 // then refresh the entire list of rows.
 function updateCursorForCell(cellId, className) {
 var cell = document.getElementById(cellId);
 // we have to go two rows back to find the cursor location
 var row = getPreviousElement(cell.parentNode);
 row.className = className;
 }
 // returns the previous element, ignores text nodes.
 function getPreviousElement(e) {
 var element = e.previousSibling;
 if (element.nodeType == 3) {
 element = element.previousSibling;
 }
 if (element && element.tagName) {
 return element;
 }
 }
 function loadCursors() {
 // register our elements with skipper
 var elements = CR_getElements('*', 'cursor_stop');
 var len = elements.length;
 for (var i = 0; i < len; i++) {
 var element = elements[i]; 
 element.className = 'cursor_stop cursor_hidden';
 kibbles.skipper.append(element);
 }
 }
 function toggleComments() {
 CR_toggleCommentDisplay();
 reloadCursors();
 }
 function keysOnLoadHandler() {
 // setup skipper
 kibbles.skipper.addStopListener(
 kibbles.skipper.LISTENER_TYPE.PRE, updateCursor);
 // Set the 'offset' option to return the middle of the client area
 // an option can be a static value, or a callback
 kibbles.skipper.setOption('padding_top', 50);
 // Set the 'offset' option to return the middle of the client area
 // an option can be a static value, or a callback
 kibbles.skipper.setOption('padding_bottom', 100);
 // Register our keys
 kibbles.skipper.addFwdKey("n");
 kibbles.skipper.addRevKey("p");
 kibbles.keys.addKeyPressListener(
 'u', function() { window.location = detail_url; });
 kibbles.keys.addKeyPressListener(
 'r', function() { window.location = detail_url + '#publish'; });
 
 kibbles.keys.addKeyPressListener('j', gotoNextPage);
 kibbles.keys.addKeyPressListener('k', gotoPreviousPage);
 
 
 }
 window.onload = function() {keysOnLoadHandler();};
 </script>


<!-- code review support -->
<script src="http://www.gstatic.com/codesite/ph/6842546122464886851/js/code_review_scripts.js"></script>
<script type="text/javascript">
 
 // the comment form template
 var form = '<div class="draft"><div class="header"><span class="title">Draft comment:</span></div>' +
 '<div class="body"><form onsubmit="return false;"><textarea id="$ID">$BODY</textarea><br>$ACTIONS</form></div>' +
 '</div>';
 // the comment "plate" template used for both draft and published comment "plates".
 var draft_comment = '<div class="draft" ondblclick="$ONDBLCLICK">' +
 '<div class="header"><span class="title">Draft comment:</span><span class="actions">$ACTIONS</span></div>' +
 '<pre id="$ID" class="body">$BODY</pre>' +
 '</div>';
 var published_comment = '<div class="published">' +
 '<div class="header"><span class="title"><a href="$PROFILE_URL">$AUTHOR:</a></span><div>' +
 '<pre id="$ID" class="body">$BODY</pre>' +
 '</div>';

 function showPublishInstructions() {
 var element = document.getElementById('review_instr');
 if (element) {
 element.className = 'opened';
 }
 }
 function revsOnLoadHandler() {
 // register our source container with the commenting code
 var paths = {'svn12': '/trunk/Makefile'}
 CR_setup('', 'p', 'duelreality', '', 'svn17', paths,
 'eb3b4fe23ef19b1e073166e328aa0525', CR_BrowseIntegrationFactory);
 // register our hidden ui elements with the code commenting code ui builder.
 CR_registerLayoutElement('form', form);
 CR_registerLayoutElement('draft_comment', draft_comment);
 CR_registerLayoutElement('published_comment', published_comment);
 
 CR_registerActivityListener(CR_ACTIVITY_TYPE.REVEAL_DRAFT_PLATE, showPublishInstructions);
 
 CR_registerActivityListener(CR_ACTIVITY_TYPE.REVEAL_PUB_PLATE, pubRevealed);
 CR_registerActivityListener(CR_ACTIVITY_TYPE.REVEAL_DRAFT_PLATE, draftRevealed);
 CR_registerActivityListener(CR_ACTIVITY_TYPE.DISCARD_DRAFT_COMMENT, draftDestroyed);
 
 
 
 
 
 
 
 
 
 var initilized = true;
 reloadCursors();
 }
 window.onload = function() {keysOnLoadHandler(); revsOnLoadHandler();};
</script>

<script type="text/javascript" src="http://www.gstatic.com/codesite/ph/6842546122464886851/js/dit_scripts_20081013.js"></script>

 
 <script type="text/javascript" src="http://www.gstatic.com/codesite/ph/6842546122464886851/js/core_scripts_20081103.js"></script>
 <script type="text/javascript" src="/js/codesite_product_dictionary_ph.pack.04102009.js"></script>
 
 
 
 </div>
<div id="footer" dir="ltr">
 
 <div class="text">
 
 &copy;2009 Google -
 <a href="/">Code Home</a> -
 <a href="/projecthosting/terms.html">Terms of Service</a> -
 <a href="http://www.google.com/privacy.html">Privacy Policy</a> -
 <a href="/more/">Site Directory</a> -
 <a href="/p/support/">Project Hosting Help</a>
 
 </div>
</div>
<script type="text/javascript">
/**
 * Reports analytics.
 * It checks for the analytics functionality (window._gat) every 100ms
 * until the analytics script is fully loaded in order to invoke siteTracker.
 */
function _CS_reportAnalytics() {
 window.setTimeout(function() {
 if (window._gat) {
 try {
 siteTracker = _gat._getTracker(CS_ANALYTICS_ACCOUNT);
 siteTracker._trackPageview();
 } catch (e) {}
 
 } else {
 _CS_reportAnalytics();
 }
 }, 100);
}
</script>

 
 
 <div class="hostedBy" style="margin-top: -20px;">
 <span style="vertical-align: top;">Hosted by</span>
 <a href="/hosting/">
 <img src="http://www.gstatic.com/codesite/ph/images/google_code_tiny.png" width="107" height="24" alt="Google Code">
 </a>
 </div>
 
 
 
 


 
 </body>
</html>

